version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: mail-service
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # Mount current directory into the container
    depends_on:
      - redis # builds the redis container first
    environment:
      - REDIS_HOST=redis # docker automatically create network where container can connect with each other using "service" name
      - REDIS_PORT=6379
      - MODE=dev
    networks:
      - backend
  
  redis:
    image: "redis:alpine"    
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # mounting redis_data /data folder inside redis container
    networks:
      - backend

volumes:
  redis_data:  # This tells Docker Compose to create a named volume called redis_data.

networks:
  backend:
    driver: bridge